/**
 * Applies pending migrations and seeds the exercise catalog.
 *
 * Both steps are idempotent, so this is safe to run on every start: the
 * migrator skips what it has already applied, and the catalog upserts on its
 * slug ids.
 *
 * Replaces `wrangler d1 migrations apply` and `wrangler d1 execute`. The
 * migrations themselves are unchanged — they were always plain SQLite DDL,
 * generated by drizzle-kit.
 */
import { readFileSync } from "node:fs";
import { mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

import SQLite from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";

const databasePath = resolve(process.env.DATABASE_PATH ?? "./data/spotter.db");

// The directory may not exist on a first run against a fresh volume.
mkdirSync(dirname(databasePath), { recursive: true });

const sqlite = new SQLite(databasePath);
sqlite.pragma("journal_mode = WAL");
sqlite.pragma("foreign_keys = ON");

const db = drizzle(sqlite);

console.log(`spotter: applying migrations to ${databasePath}`);
migrate(db, { migrationsFolder: "./drizzle/migrations" });

console.log("spotter: seeding exercise catalog");
sqlite.exec(readFileSync("./drizzle/seed/exercises.sql", "utf8"));

sqlite.close();
console.log("spotter: database ready");
