/**
 * Applies pending migrations and seeds the exercise catalog.
 *
 * Both steps are idempotent, so this is safe to run on every start: the
 * migrator skips what it has already applied, and the catalog upserts on its
 * slug ids.
 *
 * Replaces `wrangler d1 migrations apply` and `wrangler d1 execute`. The
 * migrations themselves are unchanged — they were always plain SQLite DDL,
 * generated by drizzle-kit.
 */
import { readFileSync } from "node:fs";
import { mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

import SQLite from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";

const databasePath = resolve(process.env.DATABASE_PATH ?? "./data/spotter.db");

// The directory may not exist on a first run against a fresh volume.
mkdirSync(dirname(databasePath), { recursive: true });

const sqlite = new SQLite(databasePath);
sqlite.pragma("journal_mode = WAL");

// Foreign keys are OFF while migrating. A migration that rebuilds a table drops
// the old one, and with enforcement on that drop cascades into every row
// referencing it — rebuilding `user` would delete every workout. The migrator
// runs inside a transaction, where a PRAGMA in the migration file itself is
// ignored, so it has to be set on the connection. Explicitly: better-sqlite3
// builds SQLite with enforcement on by default.
sqlite.pragma("foreign_keys = OFF");

const db = drizzle(sqlite);

console.log(`spotter: applying migrations to ${databasePath}`);
migrate(db, { migrationsFolder: "./drizzle/migrations" });

const violations = sqlite.pragma("foreign_key_check");
if (violations.length > 0) {
  console.error("spotter: foreign key violations after migrating", violations);
  process.exit(1);
}
sqlite.pragma("foreign_keys = ON");

console.log("spotter: seeding exercise catalog");
sqlite.exec(readFileSync("./drizzle/seed/exercises.sql", "utf8"));

sqlite.close();
console.log("spotter: database ready");
